### ISSUE TITLE
Weirdness with mixed-endian parsers that cross byte boundaries

### ISSUE THREAD

**Issue by mrdomino** [UpstandingHackers/hammer#118]
I ran into an utterly bizarre bug with a parser I'm writing. I've made [a gist that demonstrates it](https://gist.github.com/mrdomino/c6bc91a7cb3b9817edb5). It's not quite what I had in the initial bug, but it's the same behavior -- the lengths come out wrong on successful parses if I mix BIT_BIG_ENDIAN with a natural-endianness parser.

I was able to resolve the issue cleanly in my own parser by moving the endianness up from the individual bit-fields where possible, but it's still weird, and probably warrants investigation at some point.

**Comment by thequux** [comment]
So, first of all, switching endianness in the middle of a byte gives undefined results. I think I can fix this...
