### ISSUE TITLE
system_allocator invokes undefined behavior

### ISSUE THREAD

**Issue by pikhq** [UpstandingHackers/hammer#133]
When malloc or realloc returns NULL, in the case of out-of-memory or out-of-address-space most notably, the system_allocator functions will attempt to dereference NULL. This is likely to crash (which is itself undesirable!), but is very much undefined behavior.

**Comment by abiggerhammer** [comment]
Good catch! We'll put in checks for this ASAP and I'll close this issue when that's done. In the meantime, you can define a system_allocator with appropriate error handling for your application.
