### ISSUE TITLE
Renaming ruby binding classes

### ISSUE THREAD

**Issue by prashantbarca** [UpstandingHackers/hammer#179]
Wanted to know if the plan to rename the ruby files to `hammer-parser` is still on? 
Also, wanted to know if there are any plans to push to rubygems. 

If yes, I would volunteer!

**Comment by abiggerhammer** [comment]
It is, we just hadn't gotten around to it yet. If you'd like to tackle the renaming and pushing it to rubygems, we'll definitely welcome that PR. Thank you!

**Comment by prashantbarca** [comment]
I've pushed it to rubygems - https://rubygems.org/gems/hammer-parser . I'll add the maintainers of this project as owners there for future versions. #180 is the PR.

**Comment by abiggerhammer** [comment]
Thanks. I should have taken care of this ages ago. I merged #180 just now.
