### ISSUE TITLE
endian combinator

### ISSUE THREAD

**Issue by abiggerhammer** [UpstandingHackers/hammer#77]
Certain formats, like TIFF, can be little-endian or big-endian depending on the value of a magic byte in the header. Currently there is no way to change the endianness of an input stream mid-parse, but we can add a combinator to do this.

**Comment by mrdomino** [comment]
Is this fixed?

**Comment by abiggerhammer** [comment]
Yes, pesco did in fact fix this in #103, I just never closed it. Sorry about that.
